### ISSUE TITLE
Zone/Boss/Fly Button Mouseover.

### ISSUE THREAD

**Issue by RAtwood90** [Repooc/ElvUI_ActionBarBuddy#1]
Thanks for adding the Mouseover Option for the Actionbars.

Can u also add it to the Buttons above?

Actually if u Mousover any of this Buttons the normal Actionbars will be shown up and even though the settings shouldn't allow it.

I guess ur Plugin are also for this Buttons? Or only for Actionbars?

Thanks Repooc for ur work glad to use this Plugin.

![WoWScrnShot_070222_173641](https://user-images.githubusercontent.com/73589071/177007224-1b98abc7-c3ed-430c-9ca6-c456ed678903.jpg)

**Comment by Repooc** [comment]
there is no option for flyout button with inherit global fade.
however i didnt double check for the boss or zone button which do have inherit global fade options which i will see if i can add that if it doesnt already handle that

**Comment by Repooc** [comment]
at this time i wont be doing much for those as i will have to go test and i dont have time to hunt for a place to test since i am not really actively playing.  i would try to dry code it but i dont really want to deal with trying to do that, have u test and report back and me try something else and so on.  i will try to get around to this when i can though
